### ISSUE TITLE
unhandeled exception when admin tries to change the answer

### ISSUE THREAD

**Issue by ghost** [Goontracker/cricmybrain#11]
Login as admin
Submit the answers
Now go back and change the drop down for the winner
Click submit.

Expected result: The points of all users should get recalculated
Actual result: An error message is displayed

**Comment by pvw87** [comment]
Can you post some screenshot for this or a screen capture video?

**Comment by pvw87** [comment]
Fixed in commit 6c4ede3d1c63e287fb67eb39f210ae64f9370654
