### ISSUE TITLE
Admin cannot change previous matchDay results 

### ISSUE THREAD

**Issue by vinit-adkar** [Goontracker/cricmybrain#12]
Admin should be able to change any matchday results through Admin dashboard.

Currently if Admin is not able to enter results through current matchday, the results for that matchday become void,

**Comment by ror5chach** [comment]
There should be an option for the admin to select the match for which he wants to update/enter results.

The UI could be similar to the existing results page (where the user can select the match from a dropdown), the admin can select any match from the dropdown and be able to modify results for that game. For the admin page, this dropdown need not be limited to matches played till current matchday, it could include all the matches for the tournament.

**Comment by pvw87** [comment]
Fixed in commit: 225a283cf75d23a9896bcb29ef5b90fa2c49d7dd

Admin can now edit results for todays matches as well as previous matches
