### ISSUE TITLE
Getting todays match details does not account for all timezones and should display next day's matches

### ISSUE THREAD

**Issue by ror5chach** [Goontracker/cricmybrain#2]
In matchroutes.js

```
var cutoff = new Date();
cutoff.setHours(0,0,0,0);
cutoff = cutoff  - new Date().getTimezoneOffset()*60*1000;
var t = new Date(cutoff);
```

This will get today's date, so user will not be able to enter predictions/ view matches till matchday at 12am (midnight).
Also, check if the calculation using getTimezoneOffset() accounts for all timezones.

**Comment by pvw87** [comment]
Fixed in commit 99d800f44c9f92fbdded66dd88fb15349ad68c7e

User now have the option of viewing upcoming matches.
Todays matches will only be updated at 5pm PST/ 00:00 GMT
