### ISSUE TITLE
Unable to view matches in India windows machine after entering IST timezone in mongo.

### ISSUE THREAD

**Issue by ghost** [Goontracker/cricmybrain#5]
Issue 1: The current package does not work for IST

Issue 2: Updated package as suggested by Vinit/Pushkar, however was still unable to view macth with below JSON request

Current time in my watch is 22:37. However ,we are unable to see matches on portal for JSON request as below.

  {  
        "matchNum" : "match31",
        "date" : new Date("2016-04-11 23:30"),
        "homeTeam" : "DD",
        "awayTeam" : "RCB",
        "venue" : "SVNSIS, Raipur",
        "bonusRule" : "bonus24",
        "rule1Winner" : "",
        "rule2Winner" : "", 
        "rule3Winner" : [],
        "bonusWinner" : []
    }

On anaylsing issue the and putting the UTC time in below JSON it worked-

"_id" : ObjectId("5708c89eb1f3182deebaa0ec"), 
    "matchNum" : "match1", 
    "date" : ISODate("2016-04-10T05:30:00.000+0000"), 
    "startTimeGMT" : "23:00", 
    "homeTeam" : "MI", 
    "awayTeam" : "RPS", 
    "venue" : "Wankhede Stadium, Mumbai", 
    "bonusRule" : "bonus7", 
    "rule1Winner" : "", 
    "rule2Winner" : "", 
    "rule3Winner" : [

```
], 
"bonusWinner" : [

]
```

Please confim if its an bug
Package file is as below.

{
  "name": "cricmybrain",
  "description": "Ultimate Fantasy League for Cricket lovers !",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "nodemon ./bin/www"
  },
  "dependencies": {
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "~1.13.2",
    "connect-flash": "^0.1.1",
    "cookie-parser": "~1.3.5",
    "debug": "^2.2.0",
    "ejs": "~2.3.3",
    "express": "~4.13.1",
    "express-session": "^1.13.0",
    "method-override": "^2.3.5",
    "mongoose": "^4.4.10",
    "morgan": "~1.6.1",
    "passport": "^0.3.2",
    "passport-local": "^1.0.0",
    "serve-favicon": "~2.3.0"
  }
}

**Comment by vinit-adkar** [comment]
You have to enter matches on Server using db.matches.insert and the date field should have time in local server timezone.
When the database entry is made , it is stored in UTC format in matches collection.

Please use mongo shell/RoboMongo to add to database the JSON file as stored in InfoFolder/matchesipl2016_timezone.json instead of copying JSON from db entry
