### ISSUE TITLE
Points should be visible without horizontal scrolling

### ISSUE THREAD

**Issue by ghost** [Goontracker/cricmybrain#6]
Currently one has to scroll horizontally to see the points as below even with 100% resolution.
Can we align the griid to the left to prevent the horizontal scroll bar

![image](https://cloud.githubusercontent.com/assets/18223932/14411817/de497e3e-ff70-11e5-8463-5e48c2294c83.png)

**Comment by pvw87** [comment]
Issue has been fixed in commit #ea7e64dfe5dad74845533a641bf39ec85a9c2210
