### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by cvora23** [Goontracker/cricmybrain#9]
1: Choose the specific fantasy group instead of overall fantasy group. Make groups
2: Main thing that distinguishes this app from others is that can allow group specific rules for fantasy, so people within their own group can have fun. 
3: Overall League will have rules defined by us.  For Group Specific rules, there should be option to create allowable group rules and set them.

**Comment by vinit-adkar** [comment]
This is being managed in google doc
